[project]
name = "archive-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Timur Alimov", email = "tim.alimov@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.31.0",
    "aiosqlite>=0.22.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.0",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.ruff.lint]
extend-select = ["I"]
